spring.application.name=petcare

spring.datasource.url=jdbc:postgresql://localhost:5432/petcare
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create used only for cleaning up the database
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET:ThisIsADemoSecretKeyForLocalDevelopmentOnly2026}
jwt.expiration=3600000